# Generated by Django 4.2.7 on 2024-11-14 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos')),
                ('province', models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Manicaland', 'Manicaland'), ('Mashonaland East', 'Mashonaland East'), ('Mashonaland Central', 'Mashonaland Central'), ('Mashonaland West', 'Mashonaland West'), ('Masvingo', 'Masvingo'), ('Midlands', 'Midlands'), ('Matabeleland North', 'Matabeleland North'), ('Matabeleland South', 'Matabeleland South')], max_length=100)),
                ('country', models.CharField(choices=[('Zimbabwe', 'Zimbabwe')], max_length=100)),
                ('primary_industry', models.CharField(choices=[('Software', 'Software'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('Manufacturing', 'Manufacturing'), ('Retail', 'Retail'), ('Construction', 'Construction'), ('Education', 'Education'), ('Transportation', 'Transportation')], max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('company_size', models.CharField(choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('linkedin', models.URLField()),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
