# Generated by Django 4.2.7 on 2024-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='founded_in',
            field=models.DateField(),
        ),
    ]
