# Generated by Django 4.2.7 on 2024-10-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(choices=[('Harare', 'Harare'), ('Bulawayo', 'Bulawayo'), ('Manicaland', 'Manicaland'), ('Mashonaland East', 'Mashonaland East'), ('Mashonaland Central', 'Mashonaland Central'), ('Mashonaland West', 'Mashonaland West'), ('Masvingo', 'Masvingo'), ('Midlands', 'Midlands'), ('Matabeleland North', 'Matabeleland North'), ('Matabeleland South', 'Matabeleland South')], max_length=100)),
                ('country', models.CharField(choices=[('Zimbabwe', 'Zimbabwe')], max_length=100)),
                ('experience', models.CharField(choices=[('0 - 2', '0 - 2 years'), ('2 - 5', '2 - 5 years'), ('5 - 10', '5 - 10 years'), ('10+', '10+ years')], max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('language', models.CharField(choices=[('English', 'English'), ('Shona', 'Shona'), ('Ndebele', 'Ndebele')], max_length=100)),
                ('education_level', models.CharField(choices=[('None', 'None'), ('O Level', 'O Level'), ('Diploma', 'Diploma'), ('Bachelors', "Bachelor's Degree"), ('Masters', "Master's Degree"), ('Doctorate', 'Doctorate Degree')], max_length=100)),
                ('linkedin', models.URLField()),
                ('twitter', models.URLField()),
                ('about', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('still_working', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='resume.resume')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_type', models.CharField(choices=[('Bachelors', "Bachelor's Degree"), ('Masters', "Master's Degree"), ('Doctorate', 'Doctorate Degree')], max_length=100)),
                ('course', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('still_schooling', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=3)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='resume.resume')),
            ],
        ),
    ]
