# Generated by Django 4.2.7 on 2024-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
