# Generated by Django 4.2.7 on 2024-11-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_education_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
