# Generated by Django 4.2.7 on 2024-11-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_workexperience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
