# Generated by Django 4.2.7 on 2024-11-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_workexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
