# Generated by Django 4.2.7 on 2024-11-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_resume_video_link'),
        ('job', '0003_savejob_jobapplications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplications',
            new_name='JobApplication',
        ),
    ]
